Project/NewsPaperAdvertisementManagement/NewsPaperAdvertisementManagement/Controllers/AdminDashboardController.cs
using NewsPaperAdvertisementManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace NewsPaperAdvertisementManagement.Controllers
{
    public class AdminDashboardController : Controller
    {
       public List<Customer> customerList = new List<Customer>();
        public Customer customerDetail= new Customer();
       public  NewsPaperAgencyEntities newePaperAgencyContext = new NewsPaperAgencyEntities();
        public List<Advertisement> advertisementList = new List<Advertisement>();
        public Advertisement advertisement = new Advertisement();
        // GET: AdminDashboard
        public ActionResult Dashboard()
        {
            int adsCount = newePaperAgencyContext.Advertisements.ToList().Count();
            int confirmAds= newePaperAgencyContext.Advertisements.Where(d=>d.AdvertisementStatus.Equals("Approved")).Count();
            int totalregistration = newePaperAgencyContext.Customers.ToList().Count();
            var TotlRevenue = newePaperAgencyContext.Advertisements.Select(x => x.AdvertisementPrice);
            decimal revenue = 0;
            if(TotlRevenue !=null)
            {
                foreach(decimal item in TotlRevenue)
                {
                    revenue = item+revenue;
                }

            }
            ViewBag.revenue = revenue;
            ViewBag.adsCount = adsCount;
            ViewBag.adsConfirm = confirmAds;
            ViewBag.totalUser = totalregistration;

            return View();
        }
        [HttpGet]
        public ActionResult ViewCustomer(string searchString, string search)
        {
            if (searchString == "Name")
            {
                customerList = newePaperAgencyContext.Customers.Where(p => p.CustomerName.Contains(search)).ToList();
                return View(customerList);
            }
            else if(searchString == "Email")
            {
                customerList = newePaperAgencyContext.Customers.Where(p => p.CustomerEmailId.Contains(search)).ToList();
                return View(customerList);
            }
            else
            {
                return View(newePaperAgencyContext.Customers.ToList());
            }
            
        }
        [HttpGet]
        public async Task <ActionResult> EditCustomer(string id)
        {
            if (id != null)
            {
                customerDetail = await newePaperAgencyContext.Customers.FindAsync(id);
                return View(customerDetail);
            }
            else
            {
                return RedirectToAction("ViewCustomer");
            }
        }
        [HttpPost]
        public ActionResult EditCustomer(Customer customer)
        {
              customerDetail = newePaperAgencyContext.Customers.ToList().Find(data => data.CustomerEmailId.Equals(customer.CustomerEmailId));
                customerDetail.CustomerName = customer.CustomerName;
                customerDetail.CustomerAddress = customer.CustomerAddress;
                customerDetail.CustomerPhone = customer.CustomerPhone;
                customerDetail.CustomerEmailId = customerDetail.CustomerEmailId;
                customerDetail.CustomerPssword = customerDetail.CustomerPssword;
                newePaperAgencyContext.Configuration.ValidateOnSaveEnabled = false;
                newePaperAgencyContext.SaveChanges();
                MessageBox.Show("Edit Successful");
                return RedirectToAction("ViewCustomer");
            
              
        }


    }

}

Project/NewsPaperAdvertisementManagement/NewsPaperAdvertisementManagement/Views/AdminDashboard/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Dashboard</h2>

<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>@ViewBag.adsCount</h3>

                    <p>Total Requested Ads</p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>@ViewBag.adsConfirm@*<sup style="font-size: 20px">%</sup>*@</h3>

                    <p>Total Confirm Ads</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>@ViewBag.totalUser</h3>

                    <p>User Registrations</p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>@ViewBag.revenue RS</h3>

                    <p>Revenue Generated</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
    </div>
</div>

Project/NewsPaperAdvertisementManagement/NewsPaperAdvertisementManagement/Views/AdminDashboard/EditCustomer.cshtml
@model NewsPaperAdvertisementManagement.Models.Customer

@{
    ViewBag.Title = "Edit Customer Detail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit Detail</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style=" font-size:16px">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerEmailId)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.CustomerPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(Model => Model.CustomerPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.CustomerAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div style="text-align:center;">
                <input type="submit" value="Confirm" class="btn btn-success" style="font-size:20px" />
            </div>
        </div>
    </div>
}
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Project/NewsPaperAdvertisementManagement/NewsPaperAdvertisementManagement/Views/AdminDashboard/ViewCustomer.cshtml
@model IEnumerable<NewsPaperAdvertisementManagement.Models.Customer>

@{
    ViewBag.Title = "ViewCustomer";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>ViewCustomer</h2>
<p>
    @using (Html.BeginForm("ViewCustomer", "AdminDashboard", FormMethod.Get))
    {
    
        <b>Search By</b>@Html.RadioButton("searchString", "Name",true)<text>Customer Name</text>
        @Html.RadioButton("searchString", "Email")<text>Customer Email</text><br />
        <div>
            @Html.TextBox("search")
            <button class="btn btn-navbar" type="submit" value="search">
                <i class="fas fa-search"></i>
            </button>
        </div>
     }

</p>
<div class="card-body p-0">
    <table class="table table-striped projects">
        <thead>
            <tr>
                <th>
                    Customer Email
                </th>
                <th>
                    Customer Name
                </th>
                <th>
                    Customer Phone
                </th>
                <th>
                    Customer Address
                </th>
            </tr>
        </thead>
        @if (Model.Count() != 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.CustomerEmailId
                    </td>
                    <td>
                        @item.CustomerName
                    </td>
                    <td>
                        @item.CustomerPhone

                    </td>
                    <td>
                        @item.CustomerAddress

                    </td>
                    <td>
                    </td>
                    <td class="project-actions text-right">
                        <a class="btn btn-info btn-sm" href="@Url.Action("EditCustomer",new {id=item.CustomerEmailId +"/"})">
                            <i class="fas fa-pencil-alt">
                            </i>
                            Edit
                        </a>
                    </td>
                </tr>

            }
        }
        else
        {
            <tr>
                <td colspan="6"><h2 style="color:red">No customer Found In this detail</h2></td>
            </tr>
        }

    </table>
</div>